import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import font from 'next/font/local'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

const gilroy = font({
  src: [
    {
      path: '../assets/fonts/Gilroy-Medium.woff2',
      weight: "500",
      style: 'normal'
    },
    {
      path: '../assets/fonts/Gilroy-MediumItalic.woff2',
      weight: "500",
      style: 'italic'
    },
    {
      path: '../assets/fonts/Gilroy-Semibold.woff2',
      weight: "600",
      style: 'normal'
    },
    {
      path: '../assets/fonts/Gilroy-Bold.woff2',
      weight: "700",
      style: 'normal'
    },
  ],
  variable: '--font-gilroy'
})

export const metadata: Metadata = {
  title: 'Budbo | Cannabis, Crypto and Blockchain',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={gilroy.className}>{children}</body>
    </html>
  )
}
